### ISSUE TITLE
Email from Raksheet Bhat

### ISSUE THREAD

**Issue by gimdongwoo** [jsdevkr/react-chatview#31]
Hey, sorry to bother you like this, but I started using react-chatview recently and was wondering if you could provide an example to use 'returnScrollable' in ReactChatView.

The library is fantastic otherwise, and the only thing is that when new elements load in loadMoreHistory(), the scroll shifts down a few elements, which I want to avoid.

Thanks.

Regards,
Raksheet Bhat.

**Comment by gimdongwoo** [comment]
example for scrollPositionBottom();

```javascript
returnScrollable = (scrollable) => {
  this.setState({ scrollable });
}

render() {
  return (
    ...
    <ChatView ... returnScrollable={this.returnScrollable}>{this.state.elements}</ChatView>
    ...
  );
}

  scrollPositionBottom = () => {
    setTimeout(() => {
      const { scrollable } = this.state;
      if (scrollable) {
        const scrollHeight = scrollable.scrollHeight;
        scrollable.scrollTop = scrollHeight;
      }
    }, 500);
  }
```

**Comment by raksheetbhat** [comment]
Thanks for the swift and wonderful reply. The above function solved my problem.

**Comment by MuneebJS** [comment]
Hi @gimdongwoo,

Can you please elaborate it further?
I have this same issue but I do not understand how this heck can be implemented.
